## Pandas

## Learning Objectives

1. Inspect a Pandas dataframe to learn about its general features
2. Filter and index a Pandas dataframe to select specific rows and/or columns
3. Sort, create, update, and remove columns in a Pandas dataframe
4. Utilize `lambda` functions along with `map` and `apply` methods with Pandas dataframes
5. Summarize information in a Pandas dataframe via grouping and aggregation functions
6. Merge two Pandas dataframes

## What is Pandas?

**Pandas** is a Python library for working with structured data.

It provides tools to:
- Read data from files and databases  
- Explore and summarize datasets  
- Clean and transform variables  
- Perform data analysis  

The main data structure in Pandas is the **DataFrame**, which is similar to a spreadsheet or database table.

## Reading Files

## Reading CSV Files

Reading CSV files means importing data stored in a CSV (Comma-Separated Values) file into Python. The `pd.read_csv` function reads the file and returns a **DataFrame**, allowing the data to be explored and analyzed in Python.

In [1]:
import pandas as pd

df = pd.read_csv("../data/social_media.csv")

type(df)

pandas.core.frame.DataFrame

## Querying SQL Databases

Querying a SQL database means retrieving data from a database using SQL and loading it into Pandas. The `pd.read_sql` function runs a SQL query and returns the result as a **DataFrame**, allowing the data to be analyzed in Python.

In [2]:
import sqlite3

conn = sqlite3.connect("../data/movies.sqlite")

df_sql = pd.read_sql("""
    SELECT * FROM movies
    LIMIT 10
""", conn)

type(df_sql)

pandas.core.frame.DataFrame

## Inspecting a DataFrame

## Viewing Column Names

Viewing column names helps you see all variables available in a DataFrame. Running `df.columns` returns a list-like object containing the names of all columns in the dataset.

In [3]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
       'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
       'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
       'Mental_Health_Score', 'Relationship_Status',
       'Conflicts_Over_Social_Media', 'Addicted_Score'],
      dtype='object')

## Viewing Top/Bottom Rows

Viewing top or bottom rows allows you to quickly preview the data in a DataFrame. The functions `df.head()` and `df.tail()` return the first and last 5 rows and are useful for quickly checking what the dataset looks like.

In [4]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

## Viewing Column Information

Viewing column information helps you understand the structure of a dataset. This can be done with `df.info()` which provides names, data types, and other basic information for each column.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 705 entries, 0 to 704
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    705 non-null    int64
 1   Age                           705 non-null    int64
 2   Gender                        705 non-null    object
 3   Academic_Level                705 non-null    object
 4   Country                       705 non-null    object
 5   Avg_Daily_Usage_Hours         705 non-null    float64
 6   Most_Used_Platform            705 non-null    object
 7   Affects_Academic_Performance  705 non-null    object
 8   Sleep_Hours_Per_Night         705 non-null    float64
 9   Mental_Health_Score           705 non-null    int64
 10  Relationship_Status           705 non-null    object
 11  Conflicts_Over_Social_Media   705 non-null    int64
 12  Addicted_Score                705 non-null    int64
dtypes: float64(2), int64(5), object(6)
memory usage: 71.7+ KB

## Viewing Numeric Summaries

Viewing numeric summaries helps you quickly understand the distribution of numeric variables. The `df.describe()` function allows you to see counts, means, and more for each numeric variable.

In [6]:
df.describe()

,Student_ID,Age,Avg_Daily_Usage_Hours,Sleep_Hours_Per_Night,Mental_Health_Score,Conflicts_Over_Social_Media,Addicted_Score
count,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000
mean,353.000000,20.659574,4.918723,6.868936,6.226950,2.849645,6.436879
std,203.660256,1.399217,1.257395,1.126848,1.105055,0.957968,1.587165
min,1.000000,18.000000,1.500000,3.800000,4.000000,0.000000,2.000000
25%,177.000000,19.000000,4.100000,6.000000,5.000000,2.000000,5.000000
50%,353.000000,21.000000,4.800000,6.900000,6.000000,3.000000,7.000000
75%,529.000000,22.000000,5.800000,7.700000,7.000000,4.000000,8.000000
max,705.000000,24.000000,8.500000,9.600000,9.000000,5.000000,9.000000

## Seeing Unique Values

Seeing unique values helps you identify all distinct values that appear in a column. This can be done with `df["column"].unique()` and is especially useful for exploring **categorical variables**.

In [7]:
print(df["Relationship_Status"].unique())

print(df["Academic_Level"].unique())

['In Relationship' 'Single' 'Complicated']
['Undergraduate' 'Graduate' 'High School']

## Filtering and Indexing

## Selecting a Column

Selecting a column means extracting a single variable from a DataFrame. A column can be selected using `df["column"]`, which returns the selected column as a **Series**, allowing you to analyze or transform that variable.

In [8]:
df["Country"].head()

0    Bangladesh
1         India
2           USA
3            UK
4        Canada
Name: Country, dtype: object

## Selecting Multiple Columns

Selecting multiple columns allows you to extract more than one variable from a DataFrame at the same time. This is commonly done using `df[["column1"], ["column2"]]`.

In [9]:
df[["Age", "Academic_Level"]].head()

   Age Academic_Level
0   19  Undergraduate
1   22       Graduate
2   20  Undergraduate
3   18    High School
4   21       Graduate

## Selecting by Row's Name

Selecting by a row's name allows you to access a specific row using its label (index name). This can be done with `df.loc[row_index]`

In [10]:
df.loc[5:9]

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
5,6,19,Female,Undergraduate,Australia,7.2,Instagram,Yes,4.5,4,Complicated,5,9
6,7,23,Male,Graduate,Germany,1.5,LinkedIn,No,8.0,9,Single,0,2
7,8,20,Female,Undergraduate,Brazil,5.8,Snapchat,Yes,6.0,6,In Relationship,2,8
8,9,18,Male,High School,Japan,4.0,TikTok,No,6.5,7,Single,1,5
9,10,21,Female,Graduate,South Korea,3.3,Instagram,No,7.0,7,In Relationship,1,4

## Selecting Rows and Columns by Name

You can select a specific row and column using their labels with `.loc`. This can be done by `df.loc["row_name", "column_name"]`

In [11]:
df.loc[5:9, ["Age", "Most_Used_Platform"]]

   Age Most_Used_Platform
5   19          Instagram
6   23           LinkedIn
7   20           Snapchat
8   18             TikTok
9   21          Instagram

## Selecting a Row by Index

You can select a row based on its numeric position in the DataFrame using `.iloc`. This can be done with `df.iloc[index]`.

This returns the row located at the specified index position.

In [12]:
df.iloc[5:10]

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
5,6,19,Female,Undergraduate,Australia,7.2,Instagram,Yes,4.5,4,Complicated,5,9
6,7,23,Male,Graduate,Germany,1.5,LinkedIn,No,8.0,9,Single,0,2
7,8,20,Female,Undergraduate,Brazil,5.8,Snapchat,Yes,6.0,6,In Relationship,2,8
8,9,18,Male,High School,Japan,4.0,TikTok,No,6.5,7,Single,1,5
9,10,21,Female,Graduate,South Korea,3.3,Instagram,No,7.0,7,In Relationship,1,4

## Selecting a Column by Index

You can select a column based on its numeric position using `.iloc`. This can be done with `df.iloc[:, index]`.

This returns the column located at the specified index position.

In [13]:
df.iloc[:, [1, 6]].head()

   Age Most_Used_Platform
0   19          Instagram
1   22            Twitter
2   20             TikTok
3   18            YouTube
4   21           Facebook

## Selecting Rows and Columns by Index

You can select specific rows and columns using their numeric positions with `.iloc`. This can be done with `df.iloc[row_index, column_index]`.

This returns the value located at the specified row and column positions.

In [14]:
df.iloc[5:10, [1, 6]].head()

   Age Most_Used_Platform
5   19          Instagram
6   23           LinkedIn
7   20           Snapchat
8   18             TikTok
9   21          Instagram

## Filtering Using Conditions

You can filter rows in a DataFrame by applying a condition to a column. This can be done with `df.loc[filter_condition, "column"]`.

This returns values from the specified column for rows that satisfy the condition.

In [15]:
df.loc[df["Age"] < 20, "Most_Used_Platform"]

0      Instagram
3        YouTube
5      Instagram
8         TikTok
10      Snapchat
         ...
680    Instagram
686      Twitter
692       TikTok
698    Instagram
704     Facebook
Name: Most_Used_Platform, Length: 177, dtype: object

## Sorting

## Sorting by Column

You can sort the rows of a DataFrame based on the values in a column using `.sort_values()`. This can be done with `df.sort_values(by="column")`.

This returns the DataFrame with rows ordered according to the values in the specified column.

In [16]:
df.sort_values(by="Avg_Daily_Usage_Hours").head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
6,7,23,Male,Graduate,Germany,1.5,LinkedIn,No,8.0,9,Single,0,2
16,17,24,Male,Graduate,Sweden,2.0,LinkedIn,No,7.8,8,Single,0,3
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
28,29,24,Male,Graduate,Malaysia,2.2,LinkedIn,No,7.4,8,Single,0,3
494,495,20,Female,Undergraduate,Switzerland,2.2,Instagram,No,9.6,8,Single,2,4

## Sorting (Ascending or Descending)

You can control the sort direction using the `ascending` argument in `.sort_values()`. This can be done with `df.sort_values(by="column", ascending=True)`.

Set `ascending=True` for increasing order or `ascending=False` for decreasing order.

In [17]:
df.sort_values(by="Avg_Daily_Usage_Hours", ascending=False).head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
496,497,19,Female,Undergraduate,USA,8.5,Instagram,Yes,3.8,5,In Relationship,4,9
486,487,20,Female,Undergraduate,USA,8.4,TikTok,Yes,3.9,5,In Relationship,4,9
476,477,19,Female,Undergraduate,USA,8.3,Instagram,Yes,4.0,5,In Relationship,4,9
466,467,20,Female,Undergraduate,USA,8.2,TikTok,Yes,4.1,5,In Relationship,4,9
456,457,19,Female,Undergraduate,USA,8.1,Instagram,Yes,4.2,5,In Relationship,4,9

## Sorting by Multiple Columns

You can sort a DataFrame using more than one column. This can be done with `df.sort_values(by=["column1", "column2"])`.

Rows are first sorted by the first column, and ties are then sorted using the next column.

In [18]:
df.sort_values(by=["Age", "Gender"]).head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
13,14,18,Female,High School,Mexico,6.5,Instagram,Yes,5.5,5,Single,4,9
63,64,18,Female,High School,Czech Republic,6.1,Snapchat,Yes,5.2,4,Single,4,9
79,80,18,Female,High School,Armenia,5.9,Instagram,Yes,5.2,5,Complicated,4,9
89,90,18,Female,High School,Liechtenstein,5.8,Instagram,Yes,5.2,5,Single,4,9
103,104,18,Female,High School,Syria,5.6,Instagram,Yes,5.4,5,Single,4,8

## Manipulating Columns

## Creating Columns

You can create a new column by assigning values to a new column name. This can be done with `df["new_column"] = new_column_values`.

This adds the new column to the DataFrame.

In [19]:
df["Sleep_Usage_Ratio"] = (df["Sleep_Hours_Per_Night"] / 
                           df["Avg_Daily_Usage_Hours"])

df["Sleep_Usage_Ratio"].head()

0    1.250000
1    3.571429
2    0.833333
3    2.333333
4    1.333333
Name: Sleep_Usage_Ratio, dtype: float64

## Renaming Columns

You can rename columns in a DataFrame using `.rename()`. This can be done with `df.rename(columns={"old_name": "new_name"})`.

This changes the column name while leaving the rest of the DataFrame unchanged.

In [20]:
df.rename(columns={"Avg_Daily_Usage_Hours": "Usage",
                   "Sleep_Hours_Per_Night": "Sleep"}, inplace=True)

df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Usage,Most_Used_Platform,Affects_Academic_Performance,Sleep,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score,Sleep_Usage_Ratio
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8,1.250000
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3,3.571429
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9,0.833333
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4,2.333333
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7,1.333333

## Dropping Columns

You can remove a column from a DataFrame using `.drop()`. This can be done with `df.drop(columns="column")`.

This returns a DataFrame with the specified column removed.

In [21]:
df.drop(columns=["Student_ID", "Sleep_Usage_Ratio"], inplace=True)

df.head()

,Age,Gender,Academic_Level,Country,Usage,Most_Used_Platform,Affects_Academic_Performance,Sleep,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

## Lambda Functions

## What is a Lambda Function?

A **lambda function** is a small, anonymous function that can be defined in a single line.

In Python, lambda functions are often used for quick operations that do not require defining a full function. They are commonly used with Pandas functions like `map()` and `apply()` to transform data.

In [22]:
import numpy as np

numbers = np.array([0, 1, 2, 3, 4])

my_funct = lambda x: x**2

my_funct(numbers)

array([ 0,  1,  4,  9, 16])

## What is map?

`map()` is a Pandas method used to transform the values in a single column.

It applies a function or mapping to each value in a Series. This can be done with `df["column"].map(function)` or `df["column"].map(dictionary)`.

In [23]:
# Example of using map with a dictionary
academic_level_dict = {"High School": "HS", 
                       "Undergraduate": "U", 
                       "Graduate": "G"}

df["Academic_Level_Short"] = df["Academic_Level"].map(academic_level_dict)

# Example of using map with a function
df["Gender_Int"] = df["Gender"].map(lambda x: 1 if x == "Female" else 0)

## What is map? (Continued)

In [24]:
df[["Academic_Level", "Academic_Level_Short", "Gender", "Gender_Int"]].head()

  Academic_Level Academic_Level_Short  Gender  Gender_Int
0  Undergraduate                    U  Female           1
1       Graduate                    G    Male           0
2  Undergraduate                    U  Female           1
3    High School                   HS    Male           0
4       Graduate                    G    Male           0

## What is apply?

`apply()` is a Pandas method used to apply a function to data in a DataFrame or Series.

It is often used with lambda functions to perform operations across rows or columns. This can be done with `df.apply(function)` or `df["column"].apply(function)`.

In [25]:
df["Sleep_Usage_Ratio"] = df.apply(lambda row: 
                                   row["Sleep"]/row["Usage"], axis = 1)

df[["Sleep", "Usage", "Sleep_Usage_Ratio"]].head()

   Sleep  Usage  Sleep_Usage_Ratio
0    6.5    5.2           1.250000
1    7.5    2.1           3.571429
2    5.0    6.0           0.833333
3    7.0    3.0           2.333333
4    6.0    4.5           1.333333

## Grouping and Summarizing

## Getting Non-Null Counts

You can count the number of non-missing values in a column using `count()`. This can be done with `df["column"].count()`.

This returns the number of observations that are not null in the selected column.

In [26]:
print(df["Gender"].count())

print(df[["Gender", "Academic_Level_Short"]].count())

705
Gender                  705
Academic_Level_Short    705
dtype: int64

## Getting Category Counts

You can count how many times each value appears in a column using `value_counts()`. This can be done with `df["column"].value_counts()`.

This is commonly used to summarize **categorical variables**.

In [27]:
print(df["Academic_Level"].value_counts())

df[["Relationship_Status", "Gender"]].value_counts().head()

Academic_Level
Undergraduate    353
Graduate         325
High School       27
Name: count, dtype: int64

Relationship_Status  Gender
Single               Female    198
                     Male      186
In Relationship      Male      151
                     Female    138
Complicated          Female     17
Name: count, dtype: int64

## Getting Bivariate Categorical Counts

You can view counts for combinations of two categorical variables using `pd.crosstab()`. This can be done with `pd.crosstab(df["column1"], df["column2"])`.

This produces a table showing how frequently each pair of categories occurs.

In [28]:
pd.crosstab(df["Gender"], df["Relationship_Status"])

Relationship_Status  Complicated  In Relationship  Single
Gender
Female                        17              138     198
Male                          15              151     186

## Seeing Correlations

You can compute correlations between numeric variables using `df.corr()`.

This returns a correlation matrix showing the strength and direction of relationships between quantitative columns.

In [29]:
numeric_columns = ["Usage", "Sleep", "Conflicts_Over_Social_Media", "Addicted_Score"]

df[numeric_columns].corr()

,Usage,Sleep,Conflicts_Over_Social_Media,Addicted_Score
Usage,1.000000,-0.790582,0.804582,0.832000
Sleep,-0.790582,1.000000,-0.677266,-0.764858
Conflicts_Over_Social_Media,0.804582,-0.677266,1.000000,0.933586
Addicted_Score,0.832000,-0.764858,0.933586,1.000000

## Grouping and Summary Functions

You can group data by a variable and compute summary statistics using `groupby()`. This can be done with `df.groupby("group_column")["target_column"].function()`.

This allows you to calculate statistics such as the mean, sum, or count for each group.

In [30]:
df.groupby("Gender")["Age"].mean()

Gender
Female    19.968839
Male      21.352273
Name: Age, dtype: float64

## Group By and Aggregate

You can compute multiple summary statistics for multiple columns using `.groupby()` with `.agg()`. This can be done with `df.groupby("group_column")[["target_column1", "target_column2"]].agg(["function1", "function2"])`.

This returns grouped summaries for the selected columns using the specified functions.

In [31]:
df.groupby("Academic_Level")[["Usage", "Sleep"]].agg(["mean", "median"])

                   Usage            Sleep
                    mean median      mean median
Academic_Level
Graduate        4.776923    4.7  7.030154    7.1
High School     5.544444    5.6  5.455556    5.4
Undergraduate   5.001416    4.7  6.828612    6.8

## Group By and Aggregate

An alternative way to compute multiple summary statistics is using `.groupby()` and `.agg()` is to provide a dictionary specifying which summaries to compute for different columns. This is done with `df.groupby("group_column").agg({"target_column1": ["function1", "function2"], "target_column2": ["function1", "function2"]})`.

In [32]:
df.groupby("Academic_Level").agg({"Usage": ["mean", "median"], "Sleep": ["min", "max"]})

                   Usage        Sleep
                    mean median   min  max
Academic_Level
Graduate        4.776923    4.7   4.1  9.5
High School     5.544444    5.6   5.1  7.0
Undergraduate   5.001416    4.7   3.8  9.6

## Merging DataFrames

You can combine two DataFrames based on matching keys using `merge()`. This can be done with `df.merge(right_df, how="join_type", left_on="left_key", right_on="right_key")`. If the key names are the same for both DataFrames, you dan do `df.merge(right_df, how="merge_type", on="key")`. Inner joins are performed by default.

This joins the rows from both DataFrames where the specified keys match.

In [33]:
df_movies = pd.read_sql("""
    SELECT * FROM movies
""", conn)

df_directors = pd.read_sql("""
    SELECT * FROM directors
""", conn)

df_md = df_directors.merge(df_movies, how="left", left_on="id", right_on="director_id")

df_md.loc[0:1, ["name", "title"]]

            name    title
0  James Cameron   Avatar
1  James Cameron  Titanic

## Converting Variable to DateTime

You can convert a column to a datetime type using `pd.to_datetime()`. This can be done with `pd.to_datetime(df["date_column"])`.

This allows you to work with dates and times more easily in Pandas.

In [34]:
print(type(df_movies["release_date"][0]))

df_movies["release_date"] = pd.to_datetime(df_movies["release_date"])

print(type(df_movies["release_date"][0]))

<class 'str'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>