## Data Cleaning

## Learning Objectives

1. Handle duplicated, missing, and incomplete data
2. Clean and pre-process text data
3. Convert and manipulate data types
4. Utilize method chaining when cleaning
5. Standardize and validate data
6. Check for outliers or anomalous values

## Read and Inspect Data

We first want to read in the data and get a general sense of what we are looking at. Some questions to ask ourselves include:

- What are we trying to accomplish with our data?
- What variables are useful to us?
- What needs to be done with each variable so it can be used for modeling?

## Read and Inspect Data

In [1]:
import pandas as pd

df = pd.read_csv("../data/amazon_laptop.csv")

df.head()

,Unnamed: 0,product_title,rating,total_rating,price,next_month_bought,offer,mrp,product_details_dict,brand,...,screen_size,colour,hard_disk_size,cpu_model,ram,os,special_features,graphics_card,about,technical_details_dict
0,0,"Lenovo Yoga Slim 7, Intel Core Ultra 5 125H, 1...",4.3,(63),"85,990.",NaN,-28%,"₹81,990","{'Brand': 'Lenovo', 'Model Name': 'Yoga Slim 7...",Lenovo,...,14,Luna Grey,512 GB,Intel Core Ultra 5,16 GB,Windows 11 Home,"Anti Glare Coating, Backlit Keyboard, HD Audio",Integrated,About this itemAI Enabled Processor: Intel Cor...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."
1,1,Lenovo V15 G4 AMD Ryzen 5 7520U 15.6 inch FHD ...,4.0,(313),"38,000.",500+ boughtin past month,-27%,"₹39,999","{'Brand': 'Lenovo', 'Model Name': 'Lenovo V15'...",Lenovo,...,15.6 Inches,Gray,512 GB,Ryzen 5,16 GB,Windows 11,HD Audio,Integrated,About this itemProcessor: AMD Ryzen 5 7520U pr...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."
2,2,"BrowseBook 14.1"" FHD IPS Laptop | Best Student...",3.1,(62),"16,990.",200+ boughtin past month,-60%,"₹12,090","{'Brand': 'Neopticon', 'Model Name': 'BrowseBo...",Neopticon,...,14.1 Inches,Gray,128 GB,Celeron N4020,4 GB,Windows 11 Home,"HD Audio, Memory Card Slot",Integrated,About this itemFull HD IPS Display: The 14.1-i...,"{'Brand': '\u200eNeopticon', 'Manufacturer': '..."
3,3,"acer Aspire Lite, AMD Ryzen 3-7330U, 16GB RAM,...",3.9,"(2,071)","24,490.",400+ boughtin past month,-38%,"₹30,990","{'Brand': 'acer', 'Model Name': 'Aspire Lite',...",acer,...,15.6 Inches,Steel Gray,512 GB,Ryzen 3,16 GB,Windows 11 Home,Lightweight,Integrated,About this itemProcessor: AMD Ryzen 3 7330U pr...,"{'Brand': '\u200eacer', 'Manufacturer': '\u200..."
4,4,"ASUS Gaming V16 (2025) 14th Gen,Intel Core 7 2...",4.0,(48),"99,990.",50+ boughtin past month,-17%,"₹94,990","{'Brand': 'ASUS', 'Model Name': 'ASUS Vivobook...",ASUS,...,16 Inches,Black | Core 7 240H,512 GB,Intel Core 7,16 GB,Windows 11 Home,"Anti-glare display, Backlit Keyboard, Precisio...",Integrated,About this itemProcessor : Intel Core 7 Proces...,"{'Brand': '\u200eASUS', 'Manufacturer': '\u200..."

## Inspecting Data Types and Missing Values

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              209 non-null    int64
 1   product_title           209 non-null    object
 2   rating                  195 non-null    float64
 3   total_rating            194 non-null    object
 4   price                   209 non-null    object
 5   next_month_bought       90 non-null     object
 6   offer                   198 non-null    object
 7   mrp                     200 non-null    object
 8   product_details_dict    209 non-null    object
 9   brand                   209 non-null    object
 10  model_name              207 non-null    object
 11  screen_size             208 non-null    object
 12  colour                  209 non-null    object
 13  hard_disk_size          200 non-null    object
 14  cpu_model               204 non-null    object
 15  ram                     205 non-null    object
 16  os                      207 non-null    object
 17  special_features        201 non-null    object
 18  graphics_card           207 non-null    object
 19  about                   208 non-null    object
 20  technical_details_dict  209 non-null    object
dtypes: float64(1), int64(1), object(19)
memory usage: 34.4+ KB

## Make Initial Plan

First, we can make an initial plan for what we would like to do with each variable. Data cleaning is an iterative process so this will likely be a first pass:

- **Unnamed**: Not useful
- **product_title**: Most of information here is available elsewhere
- **rating**: Treat missing values, validate values
- **total_rating**: Extract number, treat missing values, convert data type, validate values
- **price**: Extract number, convert data type, validate values
- **next_month_bought**: Maybe remove because there are so many missing values
- **offer**: Extract number, convert data type, treat missing values, validate values
- **mrp**: Extract number, convert data type, treat missing values
- **product_details_dict**: Most information here is available elsewhere
- **brand**: Standardize categories if needed
- **model_name**: Treat missing values, maybe get model families later
- **screen_size**: Extract number, standardize scales, convert data types, treat missing value, validate values
- **colour**: Extract colour, reduce/combine categories, leave for later
- **hard_disk_size**: Extract number, standardize scales, convert data types, treat missing values, validate values
- **cpu_model**: Treat missing values, Perhaps get processor families, leave for later
- **ram**: Extract number, convert data type, treat missing values
- **os**: Standardize categories, treat missing values, perhaps combine categories later
- **special_features**: Treat missing values, extract specific features, handle later
- **graphics_card**: Treat missing values, standardize categories if needed
- **about**: Treat missing value, extract specific features, handle later
- **technical_details_dict**: Extract specific features, handle later

## Checking for Duplicates

Early on we want to check for duplicates and remove them. If an observation is duplicated many times and we include all copies when modeling, this can bias or skew our analysis. We can check for duplicates using the `duplicated` method on the entire DataFrame or a column we expect to have unique values.

In [3]:
duplicate_titles = df[df["product_title"].duplicated()]["product_title"]

df[df["product_title"] == duplicate_titles.iloc[0]]

,Unnamed: 0,product_title,rating,total_rating,price,next_month_bought,offer,mrp,product_details_dict,brand,...,screen_size,colour,hard_disk_size,cpu_model,ram,os,special_features,graphics_card,about,technical_details_dict
10,10,"Lenovo V14 Intel Core i3 13th Gen 14"" FHD (192...",3.8,(56),"41,890.",50+ boughtin past month,-47%,"₹35,990","{'Brand': 'Lenovo', 'Model Name': 'Lenovo V14'...",Lenovo,...,14 Inches,Iron Grey,512 GB,Core i3,8 GB,Windows 11 Home,"Anti Glare Coating, HD Audio, Lightweight, Spi...",Integrated,About this itemProcessor: 13th Gen Intel Core ...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."
22,22,"Lenovo V14 Intel Core i3 13th Gen 14"" FHD (192...",3.8,(56),"41,890.",50+ boughtin past month,-47%,"₹35,990","{'Brand': 'Lenovo', 'Model Name': 'Lenovo V14'...",Lenovo,...,14 Inches,Iron Grey,512 GB,Core i3,8 GB,Windows 11 Home,"Anti Glare Coating, HD Audio, Lightweight, Spi...",Integrated,About this itemProcessor: 13th Gen Intel Core ...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."
196,196,"Lenovo V14 Intel Core i3 13th Gen 14"" FHD (192...",3.8,(52),"36,990.",50+ boughtin past month,-47%,"₹35,990","{'Brand': 'Lenovo', 'Model Name': 'Lenovo V14'...",Lenovo,...,14 Inches,Iron Grey,512 GB,Core i3,8 GB,Windows 11 Home,"Anti Glare Coating, HD Audio, Lightweight, Spi...",Integrated,About this itemProcessor: 13th Gen Intel Core ...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."
199,199,"Lenovo V14 Intel Core i3 13th Gen 14"" FHD (192...",3.8,(52),"36,990.",50+ boughtin past month,-47%,"₹35,990","{'Brand': 'Lenovo', 'Model Name': 'Lenovo V14'...",Lenovo,...,14 Inches,Iron Grey,512 GB,Core i3,8 GB,Windows 11 Home,"Anti Glare Coating, HD Audio, Lightweight, Spi...",Integrated,About this itemProcessor: 13th Gen Intel Core ...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."

## Dropping Duplicates

If you decide to drop observations because they appear like duplicates, then you can use the `drop_duplicates` method. For example, `df.drop_duplicates()` which drops rows that have the same values for every column or `df.drop_duplicates(subset="column")` which drops rwos that have the same values for a specific column.

In [4]:
df.drop_duplicates(subset="product_title", inplace=True)

df

,Unnamed: 0,product_title,rating,total_rating,price,next_month_bought,offer,mrp,product_details_dict,brand,...,screen_size,colour,hard_disk_size,cpu_model,ram,os,special_features,graphics_card,about,technical_details_dict
0,0,"Lenovo Yoga Slim 7, Intel Core Ultra 5 125H, 1...",4.3,(63),"85,990.",NaN,-28%,"₹81,990","{'Brand': 'Lenovo', 'Model Name': 'Yoga Slim 7...",Lenovo,...,14,Luna Grey,512 GB,Intel Core Ultra 5,16 GB,Windows 11 Home,"Anti Glare Coating, Backlit Keyboard, HD Audio",Integrated,About this itemAI Enabled Processor: Intel Cor...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."
1,1,Lenovo V15 G4 AMD Ryzen 5 7520U 15.6 inch FHD ...,4.0,(313),"38,000.",500+ boughtin past month,-27%,"₹39,999","{'Brand': 'Lenovo', 'Model Name': 'Lenovo V15'...",Lenovo,...,15.6 Inches,Gray,512 GB,Ryzen 5,16 GB,Windows 11,HD Audio,Integrated,About this itemProcessor: AMD Ryzen 5 7520U pr...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."
2,2,"BrowseBook 14.1"" FHD IPS Laptop | Best Student...",3.1,(62),"16,990.",200+ boughtin past month,-60%,"₹12,090","{'Brand': 'Neopticon', 'Model Name': 'BrowseBo...",Neopticon,...,14.1 Inches,Gray,128 GB,Celeron N4020,4 GB,Windows 11 Home,"HD Audio, Memory Card Slot",Integrated,About this itemFull HD IPS Display: The 14.1-i...,"{'Brand': '\u200eNeopticon', 'Manufacturer': '..."
3,3,"acer Aspire Lite, AMD Ryzen 3-7330U, 16GB RAM,...",3.9,"(2,071)","24,490.",400+ boughtin past month,-38%,"₹30,990","{'Brand': 'acer', 'Model Name': 'Aspire Lite',...",acer,...,15.6 Inches,Steel Gray,512 GB,Ryzen 3,16 GB,Windows 11 Home,Lightweight,Integrated,About this itemProcessor: AMD Ryzen 3 7330U pr...,"{'Brand': '\u200eacer', 'Manufacturer': '\u200..."
4,4,"ASUS Gaming V16 (2025) 14th Gen,Intel Core 7 2...",4.0,(48),"99,990.",50+ boughtin past month,-17%,"₹94,990","{'Brand': 'ASUS', 'Model Name': 'ASUS Vivobook...",ASUS,...,16 Inches,Black | Core 7 240H,512 GB,Intel Core 7,16 GB,Windows 11 Home,"Anti-glare display, Backlit Keyboard, Precisio...",Integrated,About this itemProcessor : Intel Core 7 Proces...,"{'Brand': '\u200eASUS', 'Manufacturer': '\u200..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,201,Certified & Tested Dell Latitude E5530 Laptop ...,NaN,NaN,"10,990.",NaN,-84%,"₹13,990","{'Brand': 'Generic', 'Model Name': '5530-8-128...",Generic,...,15.6 Inches,Black,128 GB,Core i5 3340M,8 GB,Windows 10 Pro,Business Laptop,Integrated,"About this itemCertified, Cleaned & Tested: Ev...","{'Brand': '\u200eGeneric', 'Manufacturer': '\u..."
202,202,"acer Travel Lite 14[New Launch], AMD Ryzen 3-7...",4.0,(80),"40,990.",50+ boughtin past month,-33%,"₹33,490","{'Brand': 'acer', 'Model Name': 'Travel Lite',...",acer,...,14 Inches,Silver,512 GB,Ryzen 3,16 GB,Windows 11 Pro,"Anti Glare Coating, HD Audio, Lightweight, Spi...",Integrated,About this itemPower-Packed Performance – Equi...,"{'Brand': '\u200eacer', 'Manufacturer': '\u200..."
203,203,Ienovo ThinkPad T590 | InteI Core i7 8th Gen P...,NaN,NaN,"25,990.",NaN,NaN,NaN,"{'Brand': 'Generic', 'Model Name': 'Ienovo T59...",Generic,...,15.6 Inches,Black,512 GB,Core i7-8665U,16 GB,Windows 10,"Anti Glare Coating, Fingerprint Reader, Webcam",Integrated,About this itemThis product is tested to work ...,"{'Brand': '\u200eGeneric', 'Manufacturer': '\u..."
205,205,"HP Spectre x360 AI Laptop, Intel Core Ultra 7 ...",3.2,(4),"1,78,104.",NaN,NaN,NaN,"{'Brand': 'HP', 'Model Name': '16-aa0015TU', '...",HP,...,40.6 Centimetres,Black,1 TB,Intel Core Ultra 7,16 GB,Windows 11 Home,"9MP IR Camera, Backlit KB",Integrated,About this item【16-core Intel Core Ultra 7 155...,"{'Brand': '\u200eHP', 'Manufacturer': '\u200eH..."
206,206,"Lenovo IdeaPad Slim 1 AMD Ryzen 3 7320U 15.6"" ...",4.0,(512),"32,870.",NaN,-42%,"₹31,770","{'Brand': 'Lenovo', 'Model Name': 'IDEAPAD', '...",Lenovo,...,15.6 Inches,Cloud Grey - Ryzen 3 7320U | 15.6 Inch,512 GB,Ryzen 3,8 GB,Windows 11 Home,"Anti Glare Coating, HD Audio, Memory Card Slot",Integrated,About this itemProcessor:AMD Ryzen 3 7320U | S...,"{'Brand': '\u200eLenovo', 'Manufacturer': '\u2..."

## Treating Missing Values

There are many ways to deal with missing values, each with its pros and cons. Here is just a small list of simple methods:

- Remove any rows where values are missing for any variables (**listwise deletion**)
- Remove variables with a lot of missing data (**variable deletion**)
- Remove only those rows where values are missing for specific variable (**case deletion**)
- Replace missing values with a measure of central tendency (e.g., the mean, **mean imputation**)

## Treating Missing Values: Pros and Cons

| Method           |Pros                                                |Cons                        |
|------------------|----------------------------------------------------|----------------------------|
|**Listwise Deletion**|Easy, valid if data are missing completey at random |You lose a lot of data, leads to bias if data aren't missing completely at random |
|**Variable Deletion**|Easy, you don't lose any observations, useful if that variable isn't important|Problematic if that variable would have been useful for modeling|
|**Case Deletion**|Easy, valid if data missing completely at random, you don't lose as much data|You still throw away some data, can still lead to bias if there are patterns to missingness|
|**Mean Imputation**|Still Easy, valid if data are missing completely at random, you don't lose any data|Can lead to serious bias if a lot of data are missing or data aren't missing completely at random|

## Listwise Deletion

If we wanted to delete any records (rows) with any variables with missing values, we could use `df.dropna()`.

In [5]:
df_deleted = df.dropna()

df_deleted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, 1 to 202
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              55 non-null     int64
 1   product_title           55 non-null     object
 2   rating                  55 non-null     float64
 3   total_rating            55 non-null     object
 4   price                   55 non-null     object
 5   next_month_bought       55 non-null     object
 6   offer                   55 non-null     object
 7   mrp                     55 non-null     object
 8   product_details_dict    55 non-null     object
 9   brand                   55 non-null     object
 10  model_name              55 non-null     object
 11  screen_size             55 non-null     object
 12  colour                  55 non-null     object
 13  hard_disk_size          55 non-null     object
 14  cpu_model               55 non-null     object
 15  ram                     55 non-null     object
 16  os                      55 non-null     object
 17  special_features        55 non-null     object
 18  graphics_card           55 non-null     object
 19  about                   55 non-null     object
 20  technical_details_dict  55 non-null     object
dtypes: float64(1), int64(1), object(19)
memory usage: 9.5+ KB

## Variable Deletion

If we want to get rid of certain columns, we can use `df.drop(labels=["column1", "column2"], axis=1)`.

In [6]:
df.drop(labels=["Unnamed: 0", "next_month_bought", 
                "product_title", "product_details_dict",
                "technical_details_dict", "about"], axis=1, inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 141 entries, 0 to 206
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rating            128 non-null    float64
 1   total_rating      127 non-null    object
 2   price             141 non-null    object
 3   offer             133 non-null    object
 4   mrp               135 non-null    object
 5   brand             141 non-null    object
 6   model_name        140 non-null    object
 7   screen_size       140 non-null    object
 8   colour            141 non-null    object
 9   hard_disk_size    134 non-null    object
 10  cpu_model         138 non-null    object
 11  ram               139 non-null    object
 12  os                140 non-null    object
 13  special_features  133 non-null    object
 14  graphics_card     140 non-null    object
dtypes: float64(1), object(14)
memory usage: 17.6+ KB

## Case Deletion

Whenever there are variables for which it might be difficult to impute values and there isn't a lot of missing data, we can remove the rows that have missing observations just for those values. This can be done using `df.dropna(subset=["column1", "column2"]))`

In [7]:
df.dropna(subset=["model_name", "cpu_model", "os", "special_features"], inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 130 entries, 0 to 206
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rating            120 non-null    float64
 1   total_rating      119 non-null    object
 2   price             130 non-null    object
 3   offer             122 non-null    object
 4   mrp               124 non-null    object
 5   brand             130 non-null    object
 6   model_name        130 non-null    object
 7   screen_size       130 non-null    object
 8   colour            130 non-null    object
 9   hard_disk_size    128 non-null    object
 10  cpu_model         130 non-null    object
 11  ram               129 non-null    object
 12  os                130 non-null    object
 13  special_features  130 non-null    object
 14  graphics_card     130 non-null    object
dtypes: float64(1), object(14)
memory usage: 16.2+ KB

## Mean (Median, Mode) Imputation

We can impute values for a variable using some measure of central tendency. For numeric variables, we often use the mean or the median and for categorical variables we may use the mode.

For example, to impute values using the mean or median, we can do `df["column"].fillna(df["column"].mean())` or `df["column"].fillna(df["column"].median())`.

In [8]:
df["rating"] = df["rating"].fillna(df["rating"].mean())

df["rating"].describe()

count    130.000000
mean       3.871667
std        0.626444
min        1.000000
25%        3.700000
50%        3.900000
75%        4.100000
max        5.000000
Name: rating, dtype: float64

## Removing Unwanted Text/Characters

When you want to remove unwanted text or characters from a column, an easy approach is to use the `replace` method. For example, you can do `df["column"].str.replace("string pattern", "replace pattern")`

In [9]:
df["total_rating"].str.replace("(", "")

0         63)
1        313)
2         62)
3      2,071)
4         48)
        ...
201       NaN
202       80)
203       NaN
205        4)
206      512)
Name: total_rating, Length: 130, dtype: object

## Method Chaining

When we want to perform a sequence of operations, we can use **method chaining**. **Method chaining** is when multiple methods are called sequentially on a single object. For example, we can do `df["column"].method1().method2()`. You can span multiple lines by starting with `(` and ending with `)`.

In [10]:
(
    df["total_rating"].str.replace("(", "")
    .str.replace(")", "")
    .str.replace(",", "")
)

0        63
1       313
2        62
3      2071
4        48
       ...
201     NaN
202      80
203     NaN
205       4
206     512
Name: total_rating, Length: 130, dtype: object

## Data Type Conversion

Even after unwanted text or characters have been removed from a column, the column type will still be the same. If we want to treat the column as numeric, then we have to convert the data type. This can be done using `df["column"].astype("type")`. If a numeric variable has missing values, we will want to convert to the `float` data type.

In [11]:
(
    df["total_rating"].str.replace("(", "")
    .str.replace(")", "")
    .str.replace(",", "")
    .astype("float")
)

0        63.0
1       313.0
2        62.0
3      2071.0
4        48.0
        ...
201       NaN
202      80.0
203       NaN
205       4.0
206     512.0
Name: total_rating, Length: 130, dtype: float64

## Clean, Convert, and Impute via Method Chaining

A common pipeline for a column is to clean, convert, and then impute. This can be done one step at a time or we can combine method chaining and the `pipe` method. The `pipe` method lets us perform an action on an entire column at once. For example, we can do `df["column"].method1().method2().pipe(function)` to use a function on an entire column.

In [12]:
(
    df["total_rating"].str.replace("(", "")
    .str.replace(")", "")
    .str.replace(",", "")
    .astype("float")
    .pipe(lambda x: x.fillna(x.mean()))
)

0        63.000000
1       313.000000
2        62.000000
3      2071.000000
4        48.000000
          ...
201     270.016807
202      80.000000
203     270.016807
205       4.000000
206     512.000000
Name: total_rating, Length: 130, dtype: float64

## Standardizing Scales (Part I)

Different sources may report information using different metrics. In this case, it will be necessary to standardize the scales. First, we might want to determine the unit of measurement for each item. One way to do this is using `df["column"].str.contains("pattern")`.

In [13]:
df["screen_size"].str.contains("Centimetres")

0      False
1      False
2      False
3      False
4      False
       ...
201    False
202    False
203    False
205     True
206    False
Name: screen_size, Length: 130, dtype: bool

## Standardizing Scales (Part II)

Once we know what the the unit of measurement is, we can determine the multiplier for each value.

In [14]:
CM_TO_IN = 0.393701

screen_multiplier = (
    df["screen_size"].str.contains("Centimetres").
    map(lambda boolean: CM_TO_IN if boolean else 1)
)

df["screen_size"] = (
    df["screen_size"].str.replace(" Centimetres", "")
    .str.replace(" Inches", "")
    .astype("float")*screen_multiplier
)

df["screen_size"].describe()

count    130.000000
mean      15.147561
std        0.987546
min       11.600000
25%       14.003939
50%       15.600000
75%       15.600000
max       18.110246
Name: screen_size, dtype: float64

## Standardizing Categories (Part I)

Often there are multiple versions of a single category and we want to standardize them. One way to do this is to define a dictionary that assigns a common category for similar categories.

In [15]:
df["colour"].unique()

array(['Luna Grey', 'Gray', 'Steel Gray', 'Black | Core 7 240H',
       'Black, R7 | RTX 3050', 'Black', 'Mica Silver', 'Silver',
       'Iron Grey', 'R7 7735HS', 'Mecha Gray', 'Natural Silver', 'Blue',
       'Graphite Black', '2024 Aura | Ultra 7 258V', 'Platinum Silver',
       'Grey', 'Mixed Black', 'Cloud Grey', 'Off Black', 'Eclipse Gray',
       'Ryzen 7-7th Gen-16GB', 'Glacier silver',
       'R7 7735HS / Office 2024', 'Quiet Blue', 'Performance blue',
       'Corei3-13 | Blue', 'Cool Silver', 'Shadow Black', 'Carbon Grey',
       'Core Black', 'Office 2024_Blue', '12GB Natural Silver',
       'Space Black', 'Green', 'Turbo Silver', 'Ice Blue', 'Aqua',
       'Eclipse Black', 'Blue | R7 5825U', 'Cloud Grey - Ryzen 5 5500U',
       '2025 Aura | Ultra 5 226V', 'PLATINUM_GREY', 'Eclipse Grey',
       'Graphite', 'Pure White', 'Jaeger Gray', 'Arctic Grey',
       'Scandinavian White', 'Ash Grey', 'Platinum', 'Stellar Gray',
       'Silver, i5 13th Gen', 'Steel Grey',
       'Cloud Grey - Ryzen 3 7320U | 15.6 Inch'], dtype=object)

## Standardizing Categories (Part II)

In [ ]:
colour_dict = {}

colour_dict["Luna Grey"] = "Luna Grey"
colour_dict["Gray"] = "Gray"
colour_dict["Steel Gray"] = "Steel Gray"
colour_dict["Black | Core 7 240H"] = "Black"
colour_dict["Black, R7 | RTX 3050"] = "Black"
colour_dict["Black"] = "Black"
colour_dict["Mica Silver"] = "Mica Silver"
colour_dict["Silver"] = "Silver"
colour_dict["Iron Grey"] = "Iron Grey"
colour_dict["R7 7735HS"] = None
colour_dict["Mecha Gray"] = "Mecha Gray"
colour_dict["Natural Silver"] = "Natural Silver"
colour_dict["Blue"] = "Blue"
colour_dict["Graphite Black"] = "Graphite Black"
colour_dict["2024 Aura | Ultra 7 258V"] = None
colour_dict["Glacier Silver"] = "Glacier Silver"
colour_dict["Platinum Silver"] = "Platinum Silver"
colour_dict["Grey"] = "Grey"
colour_dict["Mixed Black"] = "Mixed Black"
colour_dict["Cloud Grey"] = "Cloud Grey"
colour_dict["Off Black"] = "Off Black"
colour_dict["Eclipse Gray"] = "Eclipse Gray"
colour_dict["Ryzen 7-7th Gen-16GB"] = None
colour_dict["Glacier silver"] = "Glacier Silver"
colour_dict["R7 7735HS / Office 2024"] = None
colour_dict["Quiet Blue"] = "Quiet Blue"
colour_dict["Performance blue"] = "Performance Blue"
colour_dict["Corei3-13 | Blue"] = "Blue"
colour_dict["Cool Silver"] = "Cool Silver"
colour_dict["Shadow Black"] = "Shadow Black"
colour_dict["Carbon Grey"] = "Carbon Grey"
colour_dict["Core Black"] = "Core Black"
colour_dict["Office 2024_Blue"] = "Blue"
colour_dict["12GB Natural Silver"] = "Natural Silver"
colour_dict["Space Black"] = "Space Black"
colour_dict["Green"] = "Green"
colour_dict["Turbo Silver"] = "Turbo Silver"
colour_dict["Ice Blue"] = "Ice Blue"
colour_dict["Aqua"] = "Aqua"
colour_dict["Eclipse Black"] = "Eclipse Black"
colour_dict["Blue | R7 5825U"] = "Blue"
colour_dict["Cloud Grey - Ryzen 5 5500U"] = "Cloud Grey"
colour_dict["2025 Aura | Ultra 5 226V"] = None
colour_dict["PLATINUM_GREY"] = "Platinum Grey"
colour_dict["Eclipse Grey"] = "Eclipse Grey"
colour_dict["Graphite"] = "Graphite"
colour_dict["Pure White"] = "Pure White"
colour_dict["Jaeger Gray"] = "Jaeger Gray"
colour_dict["Arctic Grey"] = "Arctic Grey"
colour_dict["Black | RTX 3050 | MSO"] = "Black"
colour_dict["Cosmos Gray"] = "Cosmos Gray"
colour_dict["Scandinavian White"] = "Scandinavian White"
colour_dict["Ash Grey"] = "Ash Grey"
colour_dict["Platinum"] = "Platinum"
colour_dict["Stellar Gray"] = "Stellar Gray"
colour_dict["Silver, i5 13th Gen"] = "Silver"
colour_dict["Steel Grey"] = "Steel Grey"
colour_dict["Translucent Black"] = "Translucent Black"
colour_dict["Cloud Grey - Ryzen 3 7320U | 15.6 Inch"] = "Cloud Grey"

df["colour"] = df["colour"].map(colour_dict)

df["colour"].unique()

## Checking for Outliers (IQR Method)

It's important to understand if there are any unusual values. One way to do this is using the IQR method. To do this you will need to use the `quantile` method. For example `df["column"].quantile()`.

In [ ]:
df["price"] = df["price"].str.replace(",", "").astype("float")

Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3-Q1

df[(df["price"] < (Q1 - 1.5*IQR)) | (df["price"] > (Q3 + 1.5*IQR))].head()

## Replacing Text with Regular Expressions (Advanced; Optional)

While you can get by cleaning text without these, regular expressions (**regex**) can be very useful and can simplify many data cleaning tasks. For example, we can provide multiple characters at once when using `df["column"].str.replace(r"([put characters here])", "replace")`

In [ ]:
df["mrp"].str.replace(r"([₹,])", "", regex=True)

## Extracting Text with Regular Expressions (Advanced; Optional)

We can also use regular expressions to extract certain patterns. This can be done using `df["column"].str.extract(r"pattern")`. In the patterns you can use character classes `[0-9]` to match digits and `[A-Za-z]` to match letters. You can also use `+` to match one or more characters.

In [ ]:
df["hard_disk_size"].str.extract(r"([A-Za-z]+)")

## Going Further with Regular Expressions (Advanced; Optional)

Regular expression provide a flexible and powerful way to match any pattern you want. The pattern below has two capture groups, each in parenthesis `()`. The `|` is used as logical OR. The `?` says that the pattern is optional. Finally, the `\s` matches a white space.

In [ ]:
import re

df["colour"].str.extract(r"""(Luna|Steel|Mica|Iron|Mecha|
                              Natural|Graphite|Glacier|Platinum|
                              Mixed|Cloud|Off|Eclipse|Quiet|Performance|
                              Cool|Shadow|Carbon|Core|SpaceTurbo|
                              Ice|Eclipse|PLATINUM|Jaeger|Arctic|
                              Cosmos|Scandinavian|Ash|Stellar|
                              Translucent)?\s?(Grey|Gray|Black|
                              Silver|Blue|Aura|silver|blue|Green|
                              Aqua|GREY|White|Platinum)?""", flags=re.VERBOSE)